name: farmmobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  get_storage: ^2.0.3
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  dotted_border: ^2.0.0+3
  step_progress_indicator: ^1.0.2
  intl: ^0.17.0
  google_fonts: ^3.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_native_splash: ^2.2.13

dev_dependencies:
  flutter_launcher_icons: "0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/drugs/
    - assets/jsons/
    - assets/treatments/
    - assets/nutritions/
    - assets/vegs/
    - assets/crops/
    - assets/fonts/  
    # - lang/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Medium.ttf

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/farm.png"
  min_sdk_android: 21
  # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"
        
flutter_native_splash:
  background_image: assets/back.png
  image: assets/pfarm.png
  android_12:
  ios: false
  web: false